name: Type-Check All Code Using Alternative Type-Checkers

"on":
    workflow_dispatch: ~

jobs:
    pyrefly:
        env:
            SKIP_MISSING_DOWNDOC: "True"
            UV_FROZEN: true
            UV_NO_SYNC: true
            UV_PYTHON_DOWNLOADS: never
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        steps:
            - uses: actions/checkout@v6

            - name: Set Up Python
              uses: actions/setup-python@v6
              with:
                python-version: ${{matrix.python-version}}

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                enable-cache: true
                python-version: ${{matrix.python-version}}

            - name: Install Pyrefly From Locked Dependencies
              run: uv sync --no-group dev --group alternative-type-checkers

            - name: Run Pyrefly
              run: uv run -- pyrefly check --output-format=github

    pyright:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: jakebailey/pyright-action@v2

    ty:
        env:
            SKIP_MISSING_DOWNDOC: "True"
            UV_FROZEN: true
            UV_NO_SYNC: true
            UV_PYTHON_DOWNLOADS: never
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        steps:
            - uses: actions/checkout@v6

            - name: Set Up Python
              uses: actions/setup-python@v6
              with:
                python-version: ${{matrix.python-version}}

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                enable-cache: true
                python-version: ${{matrix.python-version}}

            - name: Install ty From Locked Dependencies
              run: uv sync --no-group dev --group alternative-type-checkers

            - name: Run ty
              run: uv run -- ty check --output-format=github
